version: ~> 1.0

services:
    - xvfb

addons:
    apt:
      packages:
        - herbstluftwm
        - libxkbcommon-x11-0

env:
  global:
    # The name of the conda package
    - CONDA_PACKAGE="pmgr"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    - CONDA_EXTRAS="pip"
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS=""

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS=""

jobs:
  allow_failures:
    - name: "Python 3.6 - PIP"

# Modified version of the standard, we just want to deploy the conda package
language: python
os: linux
dist: xenial

stages:
  - build
  - name: deploy
    if: (branch = master OR tag IS present) AND type != pull_request

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/anaconda-build.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/anaconda-upload.yml
