{% set data = load_setup_py_data() %}

package:
  name: pmgr
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script:
    python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - pyqt >=5,<5.15
    - pyca =3.2.0
    - epicscorelibs =7.0.6.99.2.0
    - pykerberos >=1.1.14
    - mysqlclient =1.3.12|>=2.0.3
    - docopt
    - pcdsutils

test:
  imports:
    - pmgr
  commands:
    - pmgrLauncher.sh --help
    - pmgrUtils.sh --help

about:
  home: https://github.com/pcdshub/pmgr
  license: SLAC Open License
  summary:  Parameter Manager for LCLS Device Configurations
